INSERT INTO horse_breed (name) VALUES ('Arabian');
INSERT INTO horse_breed (name) VALUES ('Thoroughbred');
INSERT INTO horse_breed (name) VALUES ('Quarter Horse');
INSERT INTO horse_breed (name) VALUES ('Appaloosa');
INSERT INTO horse_breed (name) VALUES ('Andalusian');
INSERT INTO horse_breed (name) VALUES ('Friesian');
INSERT INTO horse_breed (name) VALUES ('Clydesdale');
INSERT INTO horse_breed (name) VALUES ('Shire');
INSERT INTO horse_breed (name) VALUES ('Morgan');
INSERT INTO horse_breed (name) VALUES ('Mustang');
INSERT INTO horse_breed (name) VALUES ('Paint Horse');
INSERT INTO horse_breed (name) VALUES ('Warmblood');
INSERT INTO horse_breed (name) VALUES ('Hanoverian');
INSERT INTO horse_breed (name) VALUES ('Holsteiner');
INSERT INTO horse_breed (name) VALUES ('Oldenburg');
INSERT INTO horse_breed (name) VALUES ('Icelandic Horse');
INSERT INTO horse_breed (name) VALUES ('Shetland Pony');
INSERT INTO horse_breed (name) VALUES ('Welsh Pony');
INSERT INTO horse_breed (name) VALUES ('Connemara Pony');
INSERT INTO horse_breed (name) VALUES ('Falabella');
INSERT INTO horse_breed (name) VALUES ('Lipizzaner');
INSERT INTO horse_breed (name) VALUES ('Percheron');
INSERT INTO horse_breed (name) VALUES ('Belgian Draft');
INSERT INTO horse_breed (name) VALUES ('Gypsy Vanner');
INSERT INTO horse_breed (name) VALUES ('Akhal-Teke');
INSERT INTO horse_breed (name) VALUES ('Paso Fino');
INSERT INTO horse_breed (name) VALUES ('Tennessee Walking Horse');
INSERT INTO horse_breed (name) VALUES ('Standardbred');
INSERT INTO horse_breed (name) VALUES ('Miniature Horse');
INSERT INTO horse_breed (name) VALUES ('Finnhorse');
INSERT INTO horse_breed (name) VALUES ('Knabstrupper');
INSERT INTO horse_breed (name) VALUES ('Lusitano');
INSERT INTO horse_breed (name) VALUES ('Missouri Fox Trotter');
INSERT INTO horse_breed (name) VALUES ('Norwegian Fjord');
INSERT INTO horse_breed (name) VALUES ('Trakehner');
INSERT INTO horse_breed (name) VALUES ('American Saddlebred');
INSERT INTO horse_breed (name) VALUES ('Dutch Warmblood');
INSERT INTO horse_breed (name) VALUES ('Rocky Mountain Horse');
INSERT INTO horse_breed (name) VALUES ('Camargue');
INSERT INTO horse_breed (name) VALUES ('Hackney Horse');

INSERT INTO horse_gender (name) VALUES ('Mare');
INSERT INTO horse_gender (name) VALUES ('Stallion');
INSERT INTO horse_gender (name) VALUES ('Gelding');
INSERT INTO horse_gender (name) VALUES ('Colt');
INSERT INTO horse_gender (name) VALUES ('Filly');

INSERT INTO horse_status (name) VALUES ('Active');
INSERT INTO horse_status (name) VALUES ('Resting');
INSERT INTO horse_status (name) VALUES ('In Training');
INSERT INTO horse_status (name) VALUES ('In Treatment');
INSERT INTO horse_status (name) VALUES ('Recovering');
INSERT INTO horse_status (name) VALUES ('Injured');
INSERT INTO horse_status (name) VALUES ('Sick');
INSERT INTO horse_status (name) VALUES ('Quarantined');
INSERT INTO horse_status (name) VALUES ('Retired');
INSERT INTO horse_status (name) VALUES ('Sold');
INSERT INTO horse_status (name) VALUES ('Transferred');
INSERT INTO horse_status (name) VALUES ('Pregnant');
INSERT INTO horse_status (name) VALUES ('Unavailable');
INSERT INTO horse_status (name) VALUES ('Deceased');

INSERT INTO stable_box (name) VALUES ('Standard Box');
INSERT INTO stable_box (name) VALUES ('Large Box');
INSERT INTO stable_box (name) VALUES ('Foaling Box');
INSERT INTO stable_box (name) VALUES ('Isolation Box');
INSERT INTO stable_box (name) VALUES ('Medical Box');
INSERT INTO stable_box (name) VALUES ('Pony Box');
INSERT INTO stable_box (name) VALUES ('Stallion Box');
INSERT INTO stable_box (name) VALUES ('Outdoor Box');
INSERT INTO stable_box (name) VALUES ('Indoor Box');
INSERT INTO stable_box (name) VALUES ('Corner Box');
INSERT INTO stable_box (name) VALUES ('Double Box');
INSERT INTO stable_box (name) VALUES ('Luxury Box');
INSERT INTO stable_box (name) VALUES ('Temporary Box');
INSERT INTO stable_box (name) VALUES ('Quarantine Box');
INSERT INTO stable_box (name) VALUES ('Training Box');

INSERT INTO vaccination_status (name) VALUES ('Up to Date');
INSERT INTO vaccination_status (name) VALUES ('Vaccinated');
INSERT INTO vaccination_status (name) VALUES ('Partially Vaccinated');
INSERT INTO vaccination_status (name) VALUES ('Pending Vaccination');
INSERT INTO vaccination_status (name) VALUES ('Overdue');
INSERT INTO vaccination_status (name) VALUES ('Expired');
INSERT INTO vaccination_status (name) VALUES ('Scheduled');
INSERT INTO vaccination_status (name) VALUES ('Booster Required');
INSERT INTO vaccination_status (name) VALUES ('Medical Exemption');
INSERT INTO vaccination_status (name) VALUES ('Not Vaccinated');

INSERT INTO discipline_type (name) VALUES ('Dressage');
INSERT INTO discipline_type (name) VALUES ('Show Jumping');
INSERT INTO discipline_type (name) VALUES ('Eventing');
INSERT INTO discipline_type (name) VALUES ('Cross Country');
INSERT INTO discipline_type (name) VALUES ('Endurance Riding');
INSERT INTO discipline_type (name) VALUES ('Western Riding');
INSERT INTO discipline_type (name) VALUES ('Barrel Racing');
INSERT INTO discipline_type (name) VALUES ('Reining');
INSERT INTO discipline_type (name) VALUES ('Trail Riding');
INSERT INTO discipline_type (name) VALUES ('Pleasure Riding');
INSERT INTO discipline_type (name) VALUES ('Vaulting');
INSERT INTO discipline_type (name) VALUES ('Driving');
INSERT INTO discipline_type (name) VALUES ('Mounted Games');
INSERT INTO discipline_type (name) VALUES ('Polo');
INSERT INTO discipline_type (name) VALUES ('Racing');
INSERT INTO discipline_type (name) VALUES ('Hunter');
INSERT INTO discipline_type (name) VALUES ('Equitation');
INSERT INTO discipline_type (name) VALUES ('Working Equitation');
INSERT INTO discipline_type (name) VALUES ('Therapeutic Riding');
INSERT INTO discipline_type (name) VALUES ('Liberty Training');
INSERT INTO discipline_type (name) VALUES ('Groundwork');
INSERT INTO discipline_type (name) VALUES ('Long Lining');
INSERT INTO discipline_type (name) VALUES ('Lunging');
INSERT INTO discipline_type (name) VALUES ('Obstacle Training');
INSERT INTO discipline_type (name) VALUES ('Trekking');

INSERT INTO activity_level (name) VALUES ('Very Low');
INSERT INTO activity_level (name) VALUES ('Low');
INSERT INTO activity_level (name) VALUES ('Light Work');
INSERT INTO activity_level (name) VALUES ('Moderate');
INSERT INTO activity_level (name) VALUES ('Medium Work');
INSERT INTO activity_level (name) VALUES ('Active');
INSERT INTO activity_level (name) VALUES ('High');
INSERT INTO activity_level (name) VALUES ('Intensive Training');
INSERT INTO activity_level (name) VALUES ('Competition Level');
INSERT INTO activity_level (name) VALUES ('Elite Performance');
INSERT INTO activity_level (name) VALUES ('Rehabilitation');
INSERT INTO activity_level (name) VALUES ('Resting');
INSERT INTO activity_level (name) VALUES ('Retired');

INSERT INTO categories (name) VALUES ('Veterinary');
INSERT INTO categories (name) VALUES ('Vaccination');
INSERT INTO categories (name) VALUES ('Medication');
INSERT INTO categories (name) VALUES ('Injury');
INSERT INTO categories (name) VALUES ('Illness');
INSERT INTO categories (name) VALUES ('Farrier');
INSERT INTO categories (name) VALUES ('Dental Care');
INSERT INTO categories (name) VALUES ('Training');
INSERT INTO categories (name) VALUES ('Exercise');
INSERT INTO categories (name) VALUES ('Competition');
INSERT INTO categories (name) VALUES ('Transportation');
INSERT INTO categories (name) VALUES ('Feeding');
INSERT INTO categories (name) VALUES ('Weight Check');
INSERT INTO categories (name) VALUES ('Health Check');
INSERT INTO categories (name) VALUES ('Behavior');
INSERT INTO categories (name) VALUES ('Breeding');
INSERT INTO categories (name) VALUES ('Pregnancy');
INSERT INTO categories (name) VALUES ('Foaling');
INSERT INTO categories (name) VALUES ('Equipment');
INSERT INTO categories (name) VALUES ('Stable Management');
INSERT INTO categories (name) VALUES ('Insurance');
INSERT INTO categories (name) VALUES ('Registration');
INSERT INTO categories (name) VALUES ('Ownership');
INSERT INTO categories (name) VALUES ('Travel');
INSERT INTO categories (name) VALUES ('Reminder');
INSERT INTO categories (name) VALUES ('Observation');
INSERT INTO categories (name) VALUES ('Progress Note');
INSERT INTO categories (name) VALUES ('Treatment');
INSERT INTO categories (name) VALUES ('Recovery');
INSERT INTO categories (name) VALUES ('Other');